name: 'GitHub AI Coding Agent'
description: 'AI agent that can make code changes directly to PRs based on comments'
author: 'Your Name'

branding:
  icon: 'code'
  color: 'blue'

inputs:
  openai-api-key:
    description: 'API key for OpenAI or Sonnet'
    required: false
  anthropic-api-key:
    description: 'API key for Anthropic'
    required: false
  model:
    description: 'Default AI model to use'
    required: false
    default: 'gpt-4'
  strong-model:
    description: 'Strong AI model to use for complex tasks'
    required: false
    default: ''
  weak-model:
    description: 'Weak AI model to use for simple tasks'
    required: false
    default: ''
  trigger-phrase:
    description: 'Phrase to trigger the agent'
    required: false
    default: '@github-ai-bot'
  ai-provider:
    description: 'AI provider to use (openai, sonnet, or anthropic)'
    required: false
    default: 'openai'
  queue-service-url:
    description: 'Web service URL for queue operations'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ github.token }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Run AI Agent
      env:
        GITHUB_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        COMMENT_ID: ${{ github.event.comment.id || '' }}
        COMMENT_BODY: ${{ github.event.comment.body || '' }}
        EVENT_TYPE: ${{ github.event_name }}
        AI_API_KEY: ${{ inputs.openai-api-key }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        AI_MODEL: ${{ inputs.model }}
        STRONG_AI_MODEL: ${{ inputs.strong-model }}
        WEAK_AI_MODEL: ${{ inputs.weak-model }}
        TRIGGER_PHRASE: ${{ inputs.trigger-phrase }}
        AI_PROVIDER: ${{ inputs.ai-provider }}
        QUEUE_SERVICE_URL: ${{ inputs.queue-service-url }}
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          node --experimental-modules --es-module-specifier-resolution=node src/handler.js process-pr
        elif [ "${{ github.event_name }}" == "pull_request_review_comment" ]; then
          node --experimental-modules --es-module-specifier-resolution=node src/handler.js process-review-comment
        else
          node --experimental-modules --es-module-specifier-resolution=node src/handler.js process-comment
        fi
      shell: bash
