name: AI-driven PR Response

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  process-event:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'pull_request') || (github.event_name == 'issue_comment' && github.event.issue.pull_request) }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Determine event type
        id: event-type
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "EVENT_TYPE=pull_request" >> $GITHUB_ENV
          else
            echo "EVENT_TYPE=comment" >> $GITHUB_ENV
          fi
      
      - name: Process pull request
        if: env.EVENT_TYPE == 'pull_request'
        run: node src/handler.js process-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
      
      - name: Process comment
        if: env.EVENT_TYPE == 'comment'
        run: node src/handler.js process-comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_ID: ${{ github.event.comment.id }}
          PR_NUMBER: ${{ github.event.issue.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}

