name: AI Coding Agent

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  process-event:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'pull_request') || (github.event_name == 'issue_comment') || (github.event_name == 'pull_request_review_comment') || (github.event_name == 'issues') }}
    steps:
      - name: Run AI Agent
        uses: wheeyls/pr_agent@stable
        with:
          ai-provider: 'anthropic'
          queue-service-url: ${{ secrets.QUEUE_SERVICE_URL }}
          queue-auth-token: ${{ secrets.QUEUE_AUTH_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: 'claude-3-7-sonnet-latest'
          strong-model: 'claude-3-7-sonnet-latest'
          weak-model: 'claude-3-5-haiku-latest'
          trigger-phrase: 'Hey Monty'
