name: AI Coding Agent

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
  issues:
    types: [opened]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  process-event:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'pull_request') || (github.event_name == 'issue_comment' && github.event.issue.pull_request) || (github.event_name == 'issues') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run AI Agent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          COMMENT_ID: ${{ github.event.comment.id || '' }}
          COMMENT_BODY: ${{ github.event.comment.body || '' }}
          EVENT_TYPE: ${{ github.event_name }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          AI_MODEL: 'claude-3-7-sonnet-latest'
          STRONG_AI_MODEL: 'claude-3-7-sonnet-latest'
          WEAK_AI_MODEL: 'claude-3-haiku-latest'
          TRIGGER_PHRASE: 'Hey Monty'
          AI_PROVIDER: 'anthropic'
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            node src/handler.js process-pr
          elif [ "${{ github.event_name }}" == "issues" ]; then
            node src/handler.js process-issue
          else
            node src/handler.js process-comment
          fi

